name: Build and Deploy Docker Container

on:
  push:
    branches:
      - dev
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Private Registry
        uses: docker/login-action@v2
        with:
          registry: git.stuffworks.net
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            git.stuffworks.net/psnail273/shannon-portfolio-dev:latest
            git.stuffworks.net/psnail273/shannon-portfolio-dev:${{ github.sha }}            
          build-args: |
            NEXT_PUBLIC_DEV_MODE=true
            NEXT_PUBLIC_SITE_URL=https://shannon.stuffworks.net         
          secrets: |
               DATABASE_URL=${{ secrets.DEV_DATABASE_URL }}
               AUTH_SECRET=${{ secrets.DEV_AUTH_SECRET }}
               PASSWORD=${{ secrets.DEV_PASSWORD }}
          cache-from: type=registry,ref=git.stuffworks.net/psnail273/shannon-portfolio-dev:latest
          cache-to: type=inline

      - name: Deploy container
        run: |
          docker pull git.stuffworks.net/psnail273/shannon-portfolio-dev:latest
          docker stop shannon-portfolio-dev || true
          docker rm shannon-portfolio-dev || true
          docker run -d \
            --name shannon-portfolio-dev \
            --restart unless-stopped \
            --network caddy-network \
            git.stuffworks.net/psnail273/shannon-portfolio-dev:latest          


